#!/usr/bin/env bash
# Adds permissions required for WiFi SSID detection to the Android manifest
# generated by `tauri android init`. Reading the SSID via WifiManager needs
# ACCESS_WIFI_STATE (plus runtime location permission, which the geolocation
# plugin already declares and requests).
set -euo pipefail

MANIFEST="src-tauri/gen/android/app/src/main/AndroidManifest.xml"

if [ ! -f "$MANIFEST" ]; then
  echo "error: $MANIFEST not found - run 'npx tauri android init' first" >&2
  exit 1
fi

if grep -q 'android.permission.ACCESS_WIFI_STATE' "$MANIFEST"; then
  echo "ACCESS_WIFI_STATE already present in $MANIFEST"
  exit 0
fi

sed -i 's|<uses-permission android:name="android.permission.INTERNET" */>|&\n    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />|' "$MANIFEST"

if ! grep -q 'android.permission.ACCESS_WIFI_STATE' "$MANIFEST"; then
  echo "error: failed to insert ACCESS_WIFI_STATE into $MANIFEST" >&2
  exit 1
fi

echo "Patched $MANIFEST with ACCESS_WIFI_STATE"
